version: '3'

services:
  adminer:
    image: michalhosna/adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DB: app
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: admin
      ADMINER_SERVER: database
      ADMINER_USERNAME: app
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: This will be in the title!

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"  # SMTP port
      - "1080:1080"  # Web interface port
###< symfony/mailer ###